const defaultTasks=[{text:'Review JavaScript arrays',tag:'Coding',done:false},{text:'Complete agriculture project notes',tag:'Project',done:false},{text:'Read 10 pages of a book',tag:'Personal',done:true}];
let tasks=JSON.parse(localStorage.getItem('studysprint-tasks')||'null')||defaultTasks;let sessions=Number(localStorage.getItem('studysprint-sessions')||0);let focusMinutes=Number(localStorage.getItem('studysprint-minutes')||0);let seconds=1500;let running=false;let interval=null;
const $=id=>document.getElementById(id);const taskList=$('taskList');const timer=$('timer');const status=$('sessionStatus');
function save(){localStorage.setItem('studysprint-tasks',JSON.stringify(tasks));localStorage.setItem('studysprint-sessions',sessions);localStorage.setItem('studysprint-minutes',focusMinutes)}
function renderTasks(){taskList.innerHTML='';tasks.forEach((t,i)=>{const row=document.createElement('div');row.className='task'+(t.done?' done':'');row.innerHTML=`<input type="checkbox" ${t.done?'checked':''} aria-label="Complete task"><span class="task-text">${t.text}</span><span class="task-tag">${t.tag}</span><button class="remove-task" aria-label="Remove task">×</button>`;row.querySelector('input').onchange=e=>{tasks[i].done=e.target.checked;save();renderTasks();updateSnapshot()};row.querySelector('.remove-task').onclick=()=>{tasks.splice(i,1);save();renderTasks();updateSnapshot()};taskList.appendChild(row)})}
function updateSnapshot(){$('completedCount').textContent=tasks.filter(t=>t.done).length;$('sessionCount').textContent=sessions;$('focusMinutes').textContent=focusMinutes}
function drawChart(){const values=[42,68,36,86,55,27,18];$('chartBars').innerHTML=values.map(v=>`<span class="bar" style="height:${v}%"></span>`).join('')}
function paint(){const m=String(Math.floor(seconds/60)).padStart(2,'0'),s=String(seconds%60).padStart(2,'0');timer.textContent=`${m}:${s}`;$('timerProgress').style.width=((1500-seconds)/1500*100)+'%'}
$('startBtn').onclick=()=>{if(running){running=false;clearInterval(interval);$('startBtn').textContent='Resume Focus';status.textContent='PAUSED';return}running=true;$('startBtn').textContent='Pause';status.textContent='FOCUSING';interval=setInterval(()=>{seconds--;paint();if(seconds<=0){clearInterval(interval);running=false;sessions++;focusMinutes+=25;seconds=1500;$('startBtn').textContent='Start Focus';status.textContent='COMPLETE';$('timerMessage').textContent='Great work — session completed!';save();updateSnapshot();paint()}},1000)};
$('resetBtn').onclick=()=>{clearInterval(interval);running=false;seconds=1500;$('startBtn').textContent='Start Focus';status.textContent='READY';$('timerMessage').textContent='A calm 25-minute focus sprint.';paint()};
$('addTaskBtn').onclick=()=>{const text=prompt('What do you want to focus on?');if(!text||!text.trim())return;const tag=prompt('Add a tag (for example: Study, Project, Personal)','Study')||'Study';tasks.push({text:text.trim(),tag,done:false});save();renderTasks();updateSnapshot()};
$('themeToggle').onclick=()=>{document.body.classList.toggle('dark');localStorage.setItem('studysprint-theme',document.body.classList.contains('dark')?'dark':'light')};if(localStorage.getItem('studysprint-theme')==='dark')document.body.classList.add('dark');
renderTasks();updateSnapshot();drawChart();paint();