const body=document.body;const sidebar=document.getElementById('sidebar');const menuBtn=document.getElementById('menuBtn');const themeToggle=document.getElementById('themeToggle');const themeTop=document.getElementById('themeTop');const modal=document.getElementById('modal');const addBtn=document.getElementById('addBtn');const closeModal=document.getElementById('closeModal');const form=document.getElementById('expenseForm');const list=document.getElementById('transactionList');const balanceValue=document.getElementById('balanceValue');const sideBalance=document.getElementById('sideBalance');
function setTheme(dark){body.classList.toggle('dark',dark);localStorage.setItem('budgetbloom-theme',dark?'dark':'light');if(themeToggle)themeToggle.innerHTML=dark?'☀ <span>Light mode</span>':'☾ <span>Dark mode</span>';if(themeTop)themeTop.textContent=dark?'☀':'◐'}
setTheme(localStorage.getItem('budgetbloom-theme')==='dark');
[themeToggle,themeTop].forEach(btn=>btn&&btn.addEventListener('click',()=>setTheme(!body.classList.contains('dark'))));
menuBtn&&menuBtn.addEventListener('click',()=>sidebar.classList.toggle('open'));
addBtn.addEventListener('click',()=>modal.classList.add('show'));closeModal.addEventListener('click',()=>modal.classList.remove('show'));modal.addEventListener('click',e=>{if(e.target===modal)modal.classList.remove('show')});
function money(n){return '₹'+Number(n).toLocaleString('en-IN')}
form.addEventListener('submit',e=>{e.preventDefault();const name=document.getElementById('expenseName').value.trim();const amount=Number(document.getElementById('expenseAmount').value);const category=document.getElementById('expenseCategory').value;if(!name||!amount)return;const icons={Food:'🍜',Travel:'🚕',Shopping:'🛍️',Bills:'⚡',Other:'✦'};const cls={Food:'food',Travel:'travel',Bills:'bill',Shopping:'travel',Other:'income'};const row=document.createElement('div');row.className='transaction';row.innerHTML=`<span class="txn-icon ${cls[category]}">${icons[category]}</span><div><strong>${name}</strong><small>${category} · Just now</small></div><b class="negative">−${money(amount)}</b>`;list.prepend(row);const current=Number(balanceValue.textContent.replace(/,/g,''));balanceValue.textContent=(current-amount).toLocaleString('en-IN');sideBalance.textContent=money(current-amount);form.reset();modal.classList.remove('show')});
const range=document.getElementById('rangeSelect');range.addEventListener('change',()=>{const labels=range.value==='Last 30 days'?['Week 1','Week 2','Week 3','Week 4','Today']:range.value==='This year'?['Jan','Mar','May','Jul','Sep','Now']:['Apr','May','Jun','Jul','Aug','Sep'];document.querySelectorAll('.x-labels span').forEach((el,i)=>el.textContent=labels[i%labels.length])});
